language: python


python:
  - "2.7"
  - "3.3"

env:
  - DJANGO_VERSION=1.5 SETTINGS=pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
  - DJANGO_VERSION=1.5 SETTINGS=imagemagick APT=imagemagick
  - DJANGO_VERSION=1.5 SETTINGS=graphicsmagick APT=graphicsmagick
  - DJANGO_VERSION=1.5 SETTINGS=wand APT=libmagickwand-dev PIP=wand
  - DJANGO_VERSION=1.5 SETTINGS=redis PIP=redis

  - DJANGO_VERSION=1.6 SETTINGS=pil APT='libjpeg62 libjpeg62-dev zlib1g-dev'
  - DJANGO_VERSION=1.6 SETTINGS=imagemagick APT=imagemagick
  - DJANGO_VERSION=1.6 SETTINGS=graphicsmagick APT=graphicsmagick
  - DJANGO_VERSION=1.6 SETTINGS=wand APT=libmagickwand-dev PIP=wand
  - DJANGO_VERSION=1.6 SETTINGS=redis PIP=redis

matrix:
  include:
    - python: "2.7"
      env: 
        - DJANGO_VERSION=1.5 SETTINGS=pgmagick APT='libgraphicsmagick++-dev libboost-python-dev libboost-thread-dev'
        - PIP=https://github.com/mariocesar/sorl-thumbnail/raw/wheels/wheel/pgmagick-0.5.7-cp27-none-linux_x86_64.whl

    - python: "2.7"
      env: 
        - DJANGO_VERSION=1.6 SETTINGS=pgmagick APT='libgraphicsmagick++-dev libboost-python-dev libboost-thread-dev'
        - PIP=https://github.com/mariocesar/sorl-thumbnail/raw/wheels/wheel/pgmagick-0.5.7-cp27-none-linux_x86_64.whl

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq $APT

install:
  - ./.travis.sh

script:
  - cd tests && coverage run --source=sorl runtests.py --settings=settings.$SETTINGS

after_success:
  - coveralls

services:
  - redis-server

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#sorl-thumbnail"
    on_success: change
    on_failure: change

